@Library('shared-library') _

javaunittesting(
    email: 'adilnawaz54@gmail.com',
    slackChannel: 'notificationn-channel',
    slackCredentialId: 'downtime-crew',
    repoUrl: 'https://github.com/snaatak-Downtime-Crew/salary-api.git',
    gitCredentialId: 'downtime_github'
)
